In [1]:
import pandas as pd
import numpy as np

In [12]:
u=np.array([1,2])
v=np.array([3,4])

In [13]:
z = v + u

In [25]:

np.dot(u,v)

11

In [27]:
a = np.array([[11,12,13],[21,22,23],[31,32,33]])

In [28]:
a.ndim

2

In [29]:
a.shape

(3, 3)

In [31]:
a[0]

array([11, 12, 13])

In [32]:
a=np.array([0,1])
b=np.array([1,0])
np.dot(a,b) 

0

In [33]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out


array([0, 1])

In [34]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)

In [35]:
Z

array([[2, 1],
       [1, 2]])

In [36]:
with open("Example1.txt","r") as file1:
  
    FileContent=file1.read()
    
    print(FileContent)

line 1 

line 2 

line 3
